title: 'starbuck-on-air.github.io'
description: "Personal GitHub Pages site."
baseurl:
url: "https://starbuck-on-air.github.io"

header_pages:
  - index.md
  - about.md
  - sppoki.md
  - projects.md

style: dark

footer: "We'll put something here... eventually."

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

google_analytics: G-WLW268MS29

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag