title: 'inkcartrich.github.io'
description: "Personal GitHub Pages site."
baseurl:
url: "https://inkcartrich.github.io"

header_pages:
  - index.md
  - about.md
  - spooki.md
  - vexmythoclast.md
  - projects.md

style: dark

footer: 'Follow me on <a href="https://github.com/inkcartrich">github</a>.'

# Build settings
markdown: kramdown
remote_theme: inkcartrich/jekyll-theme-console

google_analytics: G-WLW268MS29

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag